
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

/* generated by data-raw/make-callentries.R */
extern SEXP pkd_c_bitlgl_length(SEXP pkd);
extern SEXP pkd_c_bitlgl_to_logical(SEXP pkd);
extern SEXP pkd_c_bitlgl_from_logical(SEXP lgl);

static const R_CallMethodDef CallEntries[] = {
    {"pkd_c_bitlgl_length", (DL_FUNC) &pkd_c_bitlgl_length, 1},
  {"pkd_c_bitlgl_to_logical", (DL_FUNC) &pkd_c_bitlgl_to_logical, 1},
  {"pkd_c_bitlgl_from_logical", (DL_FUNC) &pkd_c_bitlgl_from_logical, 1},
  {NULL, NULL, 0}
};
/* end generated by data-raw/make-callentries.R */

void R_init_pkd(DllInfo *dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
